# Generated by Django 4.2.9 on 2024-02-11 13:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0002_category_alter_post_options_reviews_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
        migrations.AddField(
            model_name='post',
            name='ingredients',
            field=models.TextField(default=''),
        ),
    ]
